export const AccountMessages = {
  ACCOUNT_CREATED: 'Account created successfully',
  ACCOUNT_FETCHED: 'Account fetched successfully',
  ACCOUNT_UPDATED: 'Account updated successfully',
  ACCOUNT_DELETED: 'Account deleted successfully',
  ACCOUNT_NOT_CREATED: 'Account Not Created',
  ACCOUNT_NOT_DELETED: 'Failed To delete account',
  ACCOUNT_NOT_FOUND: 'Account not found',
  ACCOUNT_HAS_USERS: 'This account has users',
  ACCOUNT_CHECK_FAILED: 'Error checking account',
  ACCOUNT_IS_ALREADY_REGISTERED: 'Account is already registered',
  ACCOUNT_IS_NOT_REGISTERED: 'Account is not registered',
  User_DOESNT_HAVE_ACCOUNTS: 'This User Dont Have Accounts',
  ACCOUNT_NOT_UPDATED: 'Account Not Updated',
  ACCOUNT_UPDATED_SUCCESSFULLY: 'Account Updated Successfully',
  ACCOUNT_DETAILS_NOT_FOUND: 'Account Details Not Provided',
  ACCOUNT_DELETED_SUCCESSFULLY: 'Account Deleted Successfully',
  ACCOUNT_HAS_TRANSACTIONS: 'This account has transactions and cant be deleted',
  ACCOUNT_SENDER_NOT_FOUND: 'Account Sender Not Found',
  ACCOUNT_RECEIVER_NOT_FOUND: 'Account Receiver Not Found',
  INVALID_OBJECT_ID: 'Invalid Object Id',
};
